### ISSUE TITLE
`useParams()` returns function against type definition

### ISSUE THREAD

**Issue by timbasel** [ammarahm-ed/solid-navigation#1]
First of all this is a great library, thank you very much.

I have found an issue with the `useParams` function, in that it returns another function instead of the `params` value (despite the Typescript definition).

Here is the excerpt of the code I'm trying to use. 

```ts
// app/router.ts
declare module "solid-navigation" {
  export interface Routers {
    Default: {
      Overview: RouteDefinition;
      Details: RouteDefinition<{
        id: string;
      }>;
    };
  }
}

export const { Route, StackRouter, useParams, useRouter } = createStackRouter<"Default">();
```

```ts
// app/app.tsx
export const App = () => {
   return (
    <>
      <StackRouter initialRouteName="Overview">
        <Route name="Overview" component={OrdersOverviewPage} />
        <Route name="Details" component={OrderDetailsPage} initialParams={{ id: "12345" }} />
      </StackRouter>
    </>
  );
}
```

```ts
// app/details.tsx
import { useParams } from "./router.ts"

export const DetailsPage = () => {
  // here is the problem
  const params = useParams() // ts type of params is `{ id: string } | undefined`
  console.log(params) // but this prints `function () { [native code] }`
  //@ts-ignore
  console.log(params()) // returns  `{ "id": "12345" }` correctly

  return <stacklayout></stacklayout>
}
```

After having a quick glance at the code I suspect the additional indirection in the `ParamsContext` of being the issue.

**Comment by ammarahm-ed** [comment]
Hey Tim, I think the typings are wrong. SInce params is a function actually. I will see if I can fix this some how.

**Comment by timbasel** [comment]
For fixing the typings it should be enough to add an additional `() =>` to the `as` type cast at the end of `stack-router.tsx`.
```
 useParams: useParams as <Route extends keyof Routers[Key]>() => () => RouteParams<
      Key,
      Route
    >,
```
But what is the reason for it being a function or why do they need to be reactive? For comparison in `solid-router` `useParams` just returns the value.

**Comment by ammarahm-ed** [comment]
@timbasel I just fixed the types. Because useParams return value is a signal, it stays reactive only if it's a function much like a signal. I am not a expert at solidjs, if you think we could make it similar to solid-router, that would be great.
